name: Test
env:
  WP_FOLDER_PATH: "/tmp/wordpress"
  TOOLS_FOLDER_PATH: "~/tools"
  WP_VERSION: "latest"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - run: mysql -h 127.0.0.1 --port 8888 -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS test;'

    - name: File list
      run: ls

    - name: Print working directory
      run: pwd

    - name: Echo HOME
      run: echo $HOME

#    - name: mkdir wp folder
#      run: mkdir -p ${{env.WP_FOLDER_PATH}}

    - name: Install WP-CLI
      run: |
        mkdir ${{env.TOOLS_FOLDER_PATH}}
        # install wp-cli in the `tools` folder
        wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -P ${{env.TOOLS_FOLDER_PATH}}
        chmod +x ${{env.TOOLS_FOLDER_PATH}}/wp-cli.phar && mv ${{env.TOOLS_FOLDER_PATH}}/wp-cli.phar ${{env.TOOLS_FOLDER_PATH}}/wp
        # prepend the `tools` folder to the PATH
        # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
        echo ${{env.TOOLS_FOLDER_PATH}} >> $GITHUB_PATH
        # prepend the `vendor/bin` folder to the PATH
        echo "vendor/bin" >> $GITHUB_PATH

    - name: Install WordPress
      run: |
        mkdir -p ${{env.WP_FOLDER_PATH}}
        cd $WP_FOLDER_PATH
        wp core download --version=$WP_VERSION
        ls

    - name: Ls
      run: ls



#    - name: mysql
#      run: |
#        sudo systemctl start mysql.service
#        mysql -v

#    - name: Validate composer.json and composer.lock
#      run: composer validate --strict

#    - name: Cache Composer packages
#      id: composer-cache
#      uses: actions/cache@v2
#      with:
#        path: vendor
#        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#        restore-keys: |
#          ${{ runner.os }}-php-

#    - name: Install dependencies
#      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
